interface Data {
  id: string;
  name: string;
  birthDate: string;
  gender: 'Nam' | 'Nữ'; // Giới hạn giá trị chỉ nhận "Nam" hoặc "Nữ"
  class: string;
  retentionDate: string;
  semester: string;
  reason: string;
}
export const data: Data[] = [
  {
    id: '20206A',
    name: 'Trần Trung',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Nguyễn Ngọc Tuyết',
    birthDate: '10/10/2002',
    gender: 'Nữ',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Khám bệnh',
  },
  {
    id: '20206A',
    name: 'Hoàng Việt Cường',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Trần Thanh Tâm',
    birthDate: '10/10/2002',
    gender: 'Nữ',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Khám bệnh',
  },
  {
    id: '20206A',
    name: 'Tôn Thương Nguyệt',
    birthDate: '10/10/2002',
    gender: 'Nữ',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Nguyễn Nhật Triều',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Khám bệnh',
  },
  {
    id: '20206A',
    name: 'Trần Ngọc Diệu',
    birthDate: '10/10/2002',
    gender: 'Nữ',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Khám bệnh',
  },
  {
    id: '20206A',
    name: 'Uông Minh Minh',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Khám bệnh',
  },
  {
    id: '20206A',
    name: 'Ngọc Thanh Thanh',
    birthDate: '10/10/2002',
    gender: 'Nữ',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Khám bệnh',
  },
  {
    id: '20206A',
    name: 'Ngọc Thanh Tâm',
    birthDate: '10/10/2002',
    gender: 'Nữ',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Trần Trung',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Trần Trung',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Trần Trung',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Trần Trung',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
  {
    id: '20206A',
    name: 'Trần Trung',
    birthDate: '10/10/2002',
    gender: 'Nam',
    class: '6A',
    retentionDate: '10/10/2002',
    semester: 'Học kỳ I',
    reason: 'Gia đình có hoàn cảnh khó khăn',
  },
];
