const data = [
  {
    id: 1,
    type: 'Căn bản',
    status: 'Đã vô hiệu hóa',
    note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    disabled: true,
  },
  { id: 2, type: 'Nâng cao', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  {
    id: 3,
    type: 'Tăng cường',
    status: 'Đang hoạt động',
    note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    disabled: false,
  },
  { id: 4, type: 'Phụ đạo4', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 5, type: 'Phụ đạo5', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 6, type: 'Phụ đạo6', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 7, type: 'Phụ đạo7', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 8, type: 'Phụ đạo8', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 9, type: 'Phụ đạo9', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 10, type: 'Phụ đạo10', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 11, type: 'Phụ đạo11', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 12, type: 'Phụ đạo12', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 13, type: 'Phụ đạo13', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 14, type: 'Phụ đạo14', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 15, type: 'Phụ đạo15', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 16, type: 'Phụ đạo16', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 17, type: 'Phụ đạo17', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 18, type: 'Phụ đạo18', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 19, type: 'Phụ đạo19', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 20, type: 'Phụ đạo20', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 21, type: 'Phụ đạo21', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 22, type: 'Phụ đạo22', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
  { id: 23, type: 'Phụ đạo23', status: 'Đang hoạt động', note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', disabled: false },
];

export default data;
