interface Data {
  id: string;
  name: string;
  birthDate: string;
  gender: 'Nam' | 'Nữ';
  people: string;
  class: string;
  status: 'studying' | 'graduated' | 'classTransferred' | 'schoolTransferred' | 'dropped';
}

export const data: Data[] = [
  {
    id: '12345',
    name: 'Nguyễn Văn A',
    birthDate: '12/05/2000',
    gender: 'Nam',
    people: 'Kinh',
    class: '12A1',
    status: 'studying',
  },
  {
    id: '67890',
    name: 'Trần Thị B',
    birthDate: '25/08/2001',
    gender: 'Nữ',
    people: 'Hoa',
    class: '12A3',
    status: 'graduated',
  },
  {
    id: '24680',
    name: 'Lê Văn C',
    birthDate: '01/02/2002',
    gender: 'Nam',
    people: 'Khmer',
    class: '11B2',
    status: 'classTransferred',
  },
  {
    id: '13579',
    name: 'Hoàng Minh D',
    birthDate: '14/07/2003',
    gender: 'Nam',
    people: 'Kinh',
    class: '10C4',
    status: 'schoolTransferred',
  },
  {
    id: '98765',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '98787',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '98867',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '95767',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '91767',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '90767',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '93767',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '98767',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '98762',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '98736',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '97467',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '97629',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
  {
    id: '98762',
    name: 'Phạm Thị E',
    birthDate: '03/09/2004',
    gender: 'Nữ',
    people: 'Chăm',
    class: '9D5',
    status: 'dropped',
  },
];
