const Data = [
  {
    teacher: 'Mr. A',
    content: 'Kiểm tra 1 tiết',
    subject: 'Toán Đại Số',
    examDate: 'Thứ 5, 21/08/2020 12:00 PM',
    duration: '45 phút',
    status: 'Chưa bắt đầu',
    action: 'Bắt đầu',
  },
  {
    teacher: 'Mr. A',
    content: 'Kiểm tra 1 tiết',
    subject: 'Toán Hình học',
    examDate: 'Thứ 5, 21/08/2020 09:00 AM',
    duration: '45 phút',
    status: 'Chưa bắt đầu',
    action: 'Bắt đầu',
  },
  {
    teacher: 'Mr. A',
    content: 'Kiểm tra 1 tiết',
    subject: 'Toán Hình học',
    examDate: 'Thứ 5, 21/08/2020 09:00 AM',
    duration: '45 phút',
    status: 'Chưa bắt đầu',
    action: 'Chưa bắt đầu',
  },
  {
    teacher: 'Mr. A',
    content: 'Kiểm tra đầu giờ',
    subject: 'Toán Đại Số',
    examDate: 'Thứ 4, 20/08/2020 09:00 AM',
    duration: '15 phút',
    status: 'Đang tiến hành',
    action: 'Đang thực hiện',
  },
  {
    teacher: 'Mr. A',
    content: 'Kiểm tra 1 tiết',
    subject: 'Toán Hình học',
    examDate: 'Thứ 3, 19/08/2020 12:00 PM',
    duration: '45 phút',
    status: 'Đang tiến hành',
    action: 'Đã nộp bài',
  },
  {
    teacher: 'Mr. A',
    content: 'Kiểm tra đầu giờ',
    subject: 'Toán Đại Số',
    examDate: 'Thứ 3, 19/08/2020 09:00 AM',
    duration: '15 phút',
    status: 'Đang tiến hành',
    action: 'Chưa nộp bài',
  },
  {
    teacher: 'Mr. B',
    content: 'Kiểm tra 1 tiết',
    subject: 'Toán Hình học',
    examDate: 'Thứ 2, 18/08/2020 10:00 AM',
    duration: '45 phút',
    status: 'Đã kết thúc',
    action: 'Chưa bắt đầu',
  },
  {
    teacher: 'Mr. A',
    content: 'Kiểm tra giữa kì',
    subject: 'Toán Đại Số',
    examDate: 'Thứ 6, 15/08/2020 12:00 PM',
    duration: '45 phút',
    status: 'Đã kết thúc',
    action: 'Không nộp bài',
  },
  {
    teacher: 'Mr. B',
    content: 'Kiểm tra đầu giờ',
    subject: 'Toán Đại Số',
    examDate: 'Thứ 5, 14/08/2020 09:30 AM',
    duration: '15 phút',
    status: 'Đã kết thúc',
    action: 'Hoàn thành',
  },
  {
    teacher: 'Mr. B',
    content: 'Kiểm tra đầu giờ',
    subject: 'Toán Đại Số',
    examDate: 'Thứ 5, 14/08/2020 09:30 AM',
    duration: '15 phút',
    status: 'Đã hoàn thành',
    action: 'Đã nộp bài',
  },
];
export default Data;
